- operation: Add
  participant_description:
    name: VAGV1
    group: AUBOT_AGV
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.34999999999999998
        - 0.45000000000000001
- operation: Add
  participant_description:
    name: VAGV2
    group: AUBOT_AGV
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.34999999999999998
        - 0.45000000000000001